[package]
name = "merge-sort"
version = "0.1.0"
authors = ["Dmitriy Belyaev <mail@d-belyaev.ru>"]
edition = "2018"

[dependencies]

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "parallel"
harness = false
